using UnityEngine;
using MoreMountains.Tools;
using UnityEngine.VFX;

namespace MoreMountains.Feedbacks
{
    [AddComponentMenu("")]
    [FeedbackHelp("Control a Visual Effect as generated by a Visual Effect asset via the VFX Graph.")]
    [FeedbackPath("Visual Effects/Visual Effect")]
    public class MMF_VisualEffect : MMF_Feedback
    {
        /// a static bool used to disable all feedbacks of this type at once
        public static bool FeedbackTypeAuthorized = true;
        /// pick a color here for your feedback's inspector
#if UNITY_EDITOR
        public override Color FeedbackColor { get { return MMFeedbacksInspectorColors.DebugColor; } }
#endif
        
        [MMFInspectorGroup("VFX Target", true, 61, true)]
        /// the VFX object you want to play
        [Tooltip("the VFX object you want to play")]
        public VisualEffect VFX;

        protected override void CustomInitialization(MMF_Player owner)
        {
            base.CustomInitialization(owner);
            // your init code goes here
        }

        protected override void CustomPlayFeedback(Vector3 position, float feedbacksIntensity = 1.0f)
        {
            if (!Active || !FeedbackTypeAuthorized)
            {
                return;
            }            
            // your play code goes here
            VFX.Play();
        }

        protected override void CustomStopFeedback(Vector3 position, float feedbacksIntensity = 1)
        {
            if (!FeedbackTypeAuthorized)
            {
                return;
            }            
            VFX.Stop();
        }
    }
}